spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qq_chat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:

    db-config:
      logic-delete-field: valid # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: false # 逻辑已删除值(默认为 1)
      logic-not-delete-value: true # 逻辑未删除值(默认为 0)

lhe:
  shinano:
    qq-chat:
      start: true
      bot:
        qq: 914577981
        password: 962464HeLei.
        deviceJSONLocation: device.json
      ai:
        apiUrl: http://0.0.0.0:6667/chat

      listen-friend:
        qqList:
          - 1786934054
